# Generated by Django 3.2.8 on 2021-11-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyreview',
            options={'ordering': ('-pub_date',)},
        ),
    ]
