# Generated by Django 3.2.8 on 2021-11-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyreview',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
