# Generated by Django 3.2.8 on 2021-11-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companyreview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='company.company'),
        ),
    ]
