# Generated by Django 3.1 on 2021-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20211116_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='companyLogo/'),
        ),
    ]
