# Generated by Django 3.1 on 2021-11-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20211119_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='intro',
            field=models.CharField(max_length=1000),
        ),
    ]
