# Generated by Django 3.2.8 on 2021-11-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20211110_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicreply',
            options={'ordering': ('pub_time',)},
        ),
        migrations.AlterField(
            model_name='topicreply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='discussion.topic'),
        ),
    ]
